### ISSUE TITLE
Request : add earning release date on the quarterly results table?

### ISSUE THREAD

**Issue by pankajsays** [huskytrader/corporate-earnings#10]
ZCould you please check if you can add earning release date on the quarterly results table? This will give an idea how many days it has been since the last earning. and potentially show next earning date at appropriate place.
👍 great work on the extension.

**Comment by huskytrader** [comment]
There is currently no exact earnings date available in the quarterly data I have, just month and year. You will see Next Earnings date if you check 'Fetch fundamental data' in Options.
