### ISSUE TITLE
EPS/Earnings %Change no longer displayed 

### ISSUE THREAD

**Issue by groovyleeping** [huskytrader/corporate-earnings#11]
I have an issue where % Change now displays '-' for every stock. I have MS style %Chg output enabled.

![image](https://user-images.githubusercontent.com/31308943/176181567-6b839913-b7ba-481a-8803-f869de300eff.png)
![image](https://user-images.githubusercontent.com/31308943/176181610-5fb098a3-6a1e-4686-a1ed-b8b1a77cba53.png)

Amazing work, thanks for a great extension.

**Comment by huskytrader** [comment]
Unfortunately, it looks like seeking alpha trimmed quarters from their earnings page leaving only 4 per symbol thus making it impossible to find comparative quarter. I'll see if I can combine SA and ZA data. In the meantime, you should switch to Zacks as data source.

**Comment by huskytrader** [comment]
Original functionality is restored with release 3.2.0.
