### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by colatrader** [huskytrader/corporate-earnings#12]
Noticed in the chrome extension manager tab. Curious what the error below is. 

Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
Context
src/html/options.html
Stack Trace
src/html/options.html:0 (anonymous function)

**Comment by huskytrader** [comment]
This was caused during theme switching when script was trying to update the theme dynamically. I removed that code so the error message should disappear. Thanks for pointing this out.
