### ISSUE TITLE
Data don't show anymore

### ISSUE THREAD

**Issue by Pasqat** [huskytrader/corporate-earnings#14]
Seems all data, except earnings, don't show anymore.
I tried from two different pc, from Firefox and Brave but the result it's the same.

![image](https://github.com/huskytrader/corporate-earnings/assets/48988058/924e57bb-98b4-483b-805d-4e747b257121)

**Comment by huskytrader** [comment]
Finviz updated their site so old parsing code does not work anymore. I'll update the code in the next couple of days. Stay tuned.

**Comment by huskytrader** [comment]
I updated the code to fix the display issue. Everything works except ratings. Ratings are displayed dynamically on the new finviz site so I'll have to redesign a few things in the extension to show them. It should take a week or so.

**Comment by smelnich** [comment]
It works. Thank you very much!
