### ISSUE TITLE
Stock info missing

### ISSUE THREAD

**Issue by Tsopic** [huskytrader/corporate-earnings#18]
Hey huskey, 

Seems that the plugin have broke with news list and company info.
Only table shown.

<img width="933" alt="image" src="https://github.com/huskytrader/corporate-earnings/assets/3941909/f964fa4c-0cab-4b93-b058-ee9f32f2b54b">

<img width="259" alt="image" src="https://github.com/huskytrader/corporate-earnings/assets/3941909/ae05daa2-bbf0-41dd-a844-9d58b3f49d96">

**Comment by Tsopic** [comment]
there is no release :(

**Comment by huskytrader** [comment]
Just made one. Sorry, I forget to make explicit release sometimes. I was thinking of adding some code in the extension which will alert you if you have an outdated version.

**Comment by Tsopic** [comment]
OldTweetDech had it solved quite nicely, Seems they host .json

Or Auto Release creation Pipeline with Github Actions :)

https://github.com/dimdenGD/OldTweetDeck

<img width="916" alt="image" src="https://github.com/huskytrader/corporate-earnings/assets/3941909/2b2d0782-4e2b-4e31-8b2f-29d1cab3d3a7">


https://github.com/dimdenGD/OldTweetDeck/blob/main/src/notifications.js
