### ISSUE TITLE
Firefox install 3.2.7

### ISSUE THREAD

**Issue by lwilke** [huskytrader/corporate-earnings#19]
Hi, how do i install the 3.2.7 release using Firefox?
There is no xpi file and the FAQ only mentions copying the src tree, but is that not only for the Chrome family?

Thank you!

**Comment by huskytrader** [comment]
Submitted new version to Mozilla. As soon as it gets signed, I'll notify you,

**Comment by huskytrader** [comment]
I received the signed 3.2.7 version and when I tried it, it didn't load data fully. Sometimes there are differences between browsers in the way they parse data. I am sorry but I don't have time to figure it out and maintain a separate version for Firefox. Please use a Chrome based browser for the extension.
